server:
  name: "Travel on Chain"
  port: ":8888"
LogConfig:
  mode: 1
EthAddress:
  url: ""
mysql:
  host: "127.0.0.1"
  port: "32768"
  user: "root"
  password: "mysqlpw"
  dbname: "test"
redis:
jwt:
  key: 9OLf5jK8s