system:
  env: local
  port: 8888
  log-path: ./logs
  db-type: mysql
  use-redis: false

logrus:
  output-type: 2 # 0: stderr, 1: file, 2: both
  formatter: text
  level: info
  report-caller: true

ethereum:
  apiKeyUrl: https://arbitrum-sepolia.infura.io/v3/xxx
  contractUrl: 0xxxxxxx

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 12345678
  dbname: mysql

redis:
  useCluster: false  #是否使用redis集群模式
  addr: 127.0.0.1:6379 #使用集群模式addr和db默认无效
  password: ""
  db: 0
  clusterAddrs:
    - "172.21.0.3:7000"
    - "172.21.0.4:7001"
    - "172.21.0.2:7002"

jwt:
  key: adcde

cors:
  mode: strict-whitelist # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: "*"
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET, POST, PUT, DELETE
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值