// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accredit/getAccredit": {
            "post": {
                "description": "查询授权",
                "tags": [
                    "accredit"
                ],
                "summary": "查询授权",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "medicId",
                        "name": "medicId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "registrationId",
                        "name": "registrationId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "caseId",
                        "name": "caseId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"accredits\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/accredit/save": {
            "post": {
                "description": "新增授权",
                "tags": [
                    "accredit"
                ],
                "summary": "新增授权",
                "parameters": [
                    {
                        "description": "medicId",
                        "name": "medicId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "registrationId",
                        "name": "registrationId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "caseId",
                        "name": "caseId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/departmentList": {
            "get": {
                "description": "获取科室列表",
                "tags": [
                    "科室"
                ],
                "summary": "获取科室列表",
                "responses": {}
            }
        },
        "/api/getRecordByMedic": {
            "get": {
                "description": "获取医生挂号记录",
                "tags": [
                    "registration"
                ],
                "summary": "获取医生挂号记录",
                "parameters": [
                    {
                        "description": "医生id",
                        "name": "medicId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"挂号记录\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/getRecordByPatient": {
            "get": {
                "description": "获取患者挂号记录",
                "tags": [
                    "registration"
                ],
                "summary": "获取患者挂号记录",
                "parameters": [
                    {
                        "description": "患者id",
                        "name": "patientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"挂号记录\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/getRecordList": {
            "get": {
                "description": "获取挂号记录列表",
                "tags": [
                    "registration"
                ],
                "summary": "获取挂号记录列表",
                "parameters": [
                    {
                        "description": "患者id",
                        "name": "patientId",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "医生id",
                        "name": "medicId",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "挂号状态",
                        "name": "status",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"挂号记录\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "登录",
                "tags": [
                    "用户"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "邮箱",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"登录成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/meidcList": {
            "post": {
                "tags": [
                    "医生"
                ],
                "summary": "获取医生列表",
                "responses": {}
            }
        },
        "/api/register": {
            "post": {
                "description": "注册用户",
                "tags": [
                    "用户"
                ],
                "summary": "注册用户",
                "parameters": [
                    {
                        "description": "用户名",
                        "name": "username",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "密码",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "邮箱",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "角色",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "职业",
                        "name": "profession",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "科室",
                        "name": "departmentId",
                        "in": "body",
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/registration": {
            "post": {
                "description": "生成挂号记录",
                "tags": [
                    "registration"
                ],
                "summary": "生成挂号记录",
                "parameters": [
                    {
                        "description": "医生id",
                        "name": "medicId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "患者id",
                        "name": "patientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "挂号状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"挂号成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/updateRecordStatus": {
            "post": {
                "description": "更新挂号记录状态",
                "tags": [
                    "registration"
                ],
                "summary": "更新挂号记录状态",
                "parameters": [
                    {
                        "description": "挂号记录id",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "挂号状态",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"更新成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/case/getCaseByPatientId": {
            "get": {
                "description": "查询病例",
                "tags": [
                    "case"
                ],
                "summary": "查询病例",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "patientId",
                        "name": "patientId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": \"cases\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/case/save": {
            "post": {
                "description": "新增病例",
                "tags": [
                    "case"
                ],
                "summary": "新增病例",
                "parameters": [
                    {
                        "description": "patientId",
                        "name": "patientId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "content",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\": \"success\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
