info:
  contact: {}
paths:
  /accredit/getAccredit:
    post:
      description: 查询授权
      parameters:
      - description: medicId
        in: query
        name: medicId
        type: integer
      - description: registrationId
        in: query
        name: registrationId
        type: integer
      - description: caseId
        in: query
        name: caseId
        type: integer
      responses:
        "200":
          description: '{"data": "accredits"}'
          schema:
            type: string
      summary: 查询授权
      tags:
      - accredit
  /accredit/save:
    post:
      description: 新增授权
      parameters:
      - description: medicId
        in: body
        name: medicId
        required: true
        schema:
          type: integer
      - description: registrationId
        in: body
        name: registrationId
        required: true
        schema:
          type: integer
      - description: caseId
        in: body
        name: caseId
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "success"}'
          schema:
            type: string
      summary: 新增授权
      tags:
      - accredit
  /api/departmentList:
    get:
      description: 获取科室列表
      responses: {}
      summary: 获取科室列表
      tags:
      - 科室
  /api/getRecordByMedic:
    get:
      description: 获取医生挂号记录
      parameters:
      - description: 医生id
        in: body
        name: medicId
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: '{"data": "挂号记录"}'
          schema:
            type: string
      summary: 获取医生挂号记录
      tags:
      - registration
  /api/getRecordByPatient:
    get:
      description: 获取患者挂号记录
      parameters:
      - description: 患者id
        in: body
        name: patientId
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: '{"data": "挂号记录"}'
          schema:
            type: string
      summary: 获取患者挂号记录
      tags:
      - registration
  /api/getRecordList:
    get:
      description: 获取挂号记录列表
      parameters:
      - description: 患者id
        in: body
        name: patientId
        schema:
          type: integer
      - description: 医生id
        in: body
        name: medicId
        schema:
          type: integer
      - description: 挂号状态
        in: body
        name: status
        schema:
          type: integer
      responses:
        "200":
          description: '{"data": "挂号记录"}'
          schema:
            type: string
      summary: 获取挂号记录列表
      tags:
      - registration
  /api/login:
    post:
      description: 登录
      parameters:
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"message": "登录成功"}'
          schema:
            type: string
      summary: 登录
      tags:
      - 用户
  /api/meidcList:
    post:
      responses: {}
      summary: 获取医生列表
      tags:
      - 医生
  /api/register:
    post:
      description: 注册用户
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: 角色
        in: body
        name: role
        required: true
        schema:
          type: integer
      - description: 职业
        in: body
        name: profession
        schema:
          type: string
      - description: 科室
        in: body
        name: departmentId
        schema:
          type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 注册用户
      tags:
      - 用户
  /api/registration:
    post:
      description: 生成挂号记录
      parameters:
      - description: 医生id
        in: body
        name: medicId
        required: true
        schema:
          type: integer
      - description: 患者id
        in: body
        name: patientId
        required: true
        schema:
          type: integer
      - description: 挂号状态
        in: body
        name: status
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: '{"message": "挂号成功"}'
          schema:
            type: string
      summary: 生成挂号记录
      tags:
      - registration
  /api/updateRecordStatus:
    post:
      description: 更新挂号记录状态
      parameters:
      - description: 挂号记录id
        in: body
        name: id
        required: true
        schema:
          type: integer
      - description: 挂号状态
        in: body
        name: status
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: '{"message": "更新成功"}'
          schema:
            type: string
      summary: 更新挂号记录状态
      tags:
      - registration
  /case/getCaseByPatientId:
    get:
      description: 查询病例
      parameters:
      - description: patientId
        in: query
        name: patientId
        required: true
        type: integer
      responses:
        "200":
          description: '{"data": "cases"}'
          schema:
            type: string
      summary: 查询病例
      tags:
      - case
  /case/save:
    post:
      description: 新增病例
      parameters:
      - description: patientId
        in: body
        name: patientId
        required: true
        schema:
          type: integer
      - description: content
        in: body
        name: content
        required: true
        schema:
          type: string
      responses:
        "200":
          description: '{"msg": "success"}'
          schema:
            type: string
      summary: 新增病例
      tags:
      - case
swagger: "2.0"
